# name: RDP Login

# on: workflow_dispatch

# jobs:
#   rdp:
#     runs-on: self-hosted

#     steps:
    
#       - name: Open Notepad
#         shell: powershell
#         run: Start-Process notepad.exe -WindowStyle Normal

# name: RDP Login

# on: workflow_dispatch

# jobs:
#   rdp:
#     runs-on: self-hosted

#     steps:
#       - name: Execute Notepad Batch File
#         shell: cmd
#         run: C:\Users\ISGS-SURYA\Documents\notepad.bat


# name: RDP Login

# on: workflow_dispatch

# jobs:
#   rdp:
#     runs-on: self-hosted

#     steps:
#       - name: Execute Notepad Batch File
#         shell: cmd
#         run: |
#           echo @echo off > C:\Users\ISGS-SURYA\Documents\notepad.bat
#           echo start notepad.exe >> C:\Users\ISGS-SURYA\Documents\notepad.bat
#           echo exit >> C:\Users\ISGS-SURYA\Documents\notepad.bat
#           C:\Users\ISGS-SURYA\Documents\notepad.bat


name: RDP Login

on: workflow_dispatch

jobs:
  rdp:
    runs-on: self-hosted

    steps:
      - name: Jalankan File Batch
        shell: cmd
        # run: C:\Users\ISGS-SURYA\Documents\notepad.bat
        # run: C:\Windows\System32\PsExec64.exe -accepteula -i 2 -s notepad.exe
        run: C:\Windows\System32\PsExec64.exe -accepteula -i 2 -s -d C:\Users\ISGS-SURYA\Documents\notepad.bat

