name: RDP Login

on: workflow_dispatch

jobs:
  rdp:
    runs-on: self-hosted

    steps:
    
      - name: Open Notepad
        shell: powershell
        run: Start-Process notepad.exe -WindowStyle Normal

