name: RDP Login

on: workflow_dispatch

jobs:
  rdp:
    runs-on: self-hosted

    steps:
      - name: Save RDP Credentials
        run: |
          cmdkey /generic:172.16.14.130 /user:Administrator /pass:"Password1234"
