name: RDP Login

on: workflow_dispatch

jobs:
  rdp:
    runs-on: self-hosted

    steps:
      - name: Save RDP Credentials
        run: cmdkey /generic:103.250.10.8 /user:Administrator /pass:P@ssw0rd

      - name: Connect via RDP
        run: mstsc /v:172.16.14.132
