name: SSH Whoami

on: workflow_dispatch

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH command
        uses: appleboy/ssh-action@v1
        with:
          host: 172.16.14.132
          username: root
          password: P@ssw0rd
          port: 22
          script: whoami
